# Generated by Django 5.2.7 on 2025-12-21 23:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('general', 'General'), ('electronics-and-technology', 'Electronics & Technology'), ('fashion-and-beauty', 'Fashion & Beauty'), ('home-and-living', 'Home & Living'), ('sports-and-outdoors', 'Sports & Outdoors'), ('health-and-personal-care', 'Health & Personal Care'), ('baby-kids-and-toys', 'Baby Kids & Toys'), ('groceries-and-essentials', 'Groceries & Essentials'), ('automotive-and-industrial', 'Automotive & Industrial'), ('books-and-stationery', 'Books & Stationery'), ('gaming-and-entertainment', 'Gaming & Entertainment'), ('pet-supplies', 'Pet Supplies'), ('office-and-business', 'Office & Business'), ('art-and-craft', 'Art & Craft'), ('jewelry-and-accessories', 'Jewelry & Accessories'), ('appliances', 'Appliances'), ('hardware-and-diy', 'Hardware & DIY'), ('music-and-instruments', 'Music & Instruments')], default='general', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='product.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
