# Generated by Django 5.2.7 on 2025-12-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'permissions': [('list_products', 'list all products'), ('list_approved_products', 'list only approved products'), ('list_unapproved_products', 'list only unapproved products'), ('view_product_details', 'view the details of a product'), ('create_product', 'can create product'), ('update_product_details', 'can update product details'), ('approve_product', 'can approve products'), ('disprove_product', 'can disprove products')]},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('review_product', 'can review a product'), ('edit review', 'can edit self review'), ('view_reviews', 'can view all reviews for a product'), ('delete_any_review', 'can delete any product review')]},
        ),
    ]
