# Generated by Django 5.2.7 on 2026-01-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitems_product_id'),
        ('dispute', '0003_alter_disputes_product'),
        ('product', '0003_remove_products_category_remove_products_user_and_more'),
        ('purchase', '0003_alter_orderitems_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
