# Generated by Django 5.2.7 on 2026-01-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blacklisted', 'Blacklisted'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
