# Generated by Django 5.2.7 on 2025-12-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('create_order', 'can create order'), ('cancel_order', 'can cancel order'), ('save_order', 'can save order'), ('view_all_orders', 'can view all orders'), ('view_order_item', 'can view order item'), ('edit_order', 'can edit order'), ('pay_order', 'can pay for order'), ('confirm_payment', 'can confirm order payment'), ('generate_reciept', 'can generate reciept for order'), ('deliver_order', 'can_deliver_order'), ('view_delivery_details', 'can view delivery details'), ('recieve_order_delivery', 'can recieve order delivery')]},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('not_paid', 'Not Paid'), ('saved', 'Saved')], default='not_paid'),
        ),
    ]
