# Generated by Django 5.2.7 on 2026-01-08 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitems_seller_usercart_is_active_and_more'),
        ('product', '0005_alter_product_status'),
        ('purchase', '0004_order_session_key_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.usercart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved for Later'), ('awaiting_payment', 'Awaiting Payment'), ('payment_pending', 'Payment Pending Confirmation'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='delivery', to='purchase.order'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('en_route', 'En Route'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='processing', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='orderitems',
            unique_together={('order', 'product')},
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('session_key__isnull', False), _connector='OR'), name='order_owner_required'),
        ),
    ]
