# Generated by Django 5.2.7 on 2025-12-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disputes',
            options={'permissions': [('create_dispute', 'can create dispute'), ('view_self_disputes', 'can view self disputes'), ('cancel_dispute', 'can cancel dispute'), ('escalate_dispute', 'can escalate dispute'), ('satisfy_dispute', 'can get satisfied by the dispute'), ('acknowledge_dispute', 'can acknowledge disputes'), ('respond_to_dispute', 'can respond to dispute'), ('resolve_dispute', 'can resolve dispute'), ('view_escalated_disputes', 'can view escalated disputes'), ('resolve_escalated_disputes', 'can resolve escalated disputes')]},
        ),
    ]
