# Generated by Django 5.2.7 on 2026-01-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispute', '0002_alter_disputes_options'),
        ('product', '0003_remove_products_category_remove_products_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputes',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='product.product'),
        ),
    ]
