# Generated by Django 5.2.7 on 2025-12-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katakara_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='katakarauser',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='katakarauser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
