# Generated by Django 5.2.7 on 2025-12-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katakara_auth', '0002_katakarauser_bio_alter_katakarauser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='katakarauser',
            options={'permissions': [('user_account_detail', 'can view self account details'), ('user_account_update', 'can update account details'), ('user_role_update', 'can update account role'), ('user_activate_account', 'can activate self account'), ('user_decativate_account', 'can deactivate self account'), ('user_change_password', 'can change password'), ('user_list_accounts', 'can view all users'), ('user_approve_role', 'can approve role for user'), ('user_ban_account', 'can ban account'), ('user_unban_account', 'can unban account')]},
        ),
    ]
