# Generated by Django 5.2.7 on 2026-01-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katakara_auth', '0004_create_groups_and_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedTokens',
        ),
    ]
