# Generated by Django 5.2.7 on 2026-01-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katakara_auth', '0005_delete_blacklistedtokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katakarauser',
            name='username',
        ),
    ]
