# Generated by Django 5.2.7 on 2026-01-09 15:58

from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model("katakara_auth", "Role")

    roles = ["buyer", "seller", "admin", "superadmin"]

    for role_name in roles:
        Role.objects.get_or_create(name=role_name)

class Migration(migrations.Migration):

    dependencies = [
        ('katakara_auth', '0007_roleupgraderequest'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
