# Generated by Django 5.2.7 on 2025-12-23 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercart',
            options={'permissions': [('clear_cart', 'can clear cart'), ('add_item_to_cart', 'can add item to cart'), ('remove_item_from_cart', 'can remove item from cart')]},
        ),
    ]
