# Generated by Django 5.2.7 on 2026-01-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_usercart_options'),
        ('product', '0003_remove_products_category_remove_products_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
