# Generated by Django 5.2.7 on 2026-01-07 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitems_product_id'),
        ('product', '0005_alter_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.usercart', default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        # Move this LAST - after cart field is added!
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart', 'product')},
        ),
    ]
